/**
 * 200 cities — hardcoded metrics aligned to Numbeo 2025 snapshots (indices, USD rent, climate normals).
 * income_tax_rate: approximate top effective bracket for wage earners / common expat regime (not tax advice).
 */
export type CityRow = {
  name: string
  country: string
  continent: string
  flag: string
  avg_temp_celsius: number
  income_tax_rate: number
  rent_1bed_usd: number
  safety_index: number
  healthcare_index: number
}

export const CITIES: CityRow[] = [
  { name: "Dubai", country: "United Arab Emirates", continent: "Asia", flag: "🇦🇪", avg_temp_celsius: 28, income_tax_rate: 0, rent_1bed_usd: 1850, safety_index: 84, healthcare_index: 72 },
  { name: "Abu Dhabi", country: "United Arab Emirates", continent: "Asia", flag: "🇦🇪", avg_temp_celsius: 27, income_tax_rate: 0, rent_1bed_usd: 1600, safety_index: 88, healthcare_index: 76 },
  { name: "Doha", country: "Qatar", continent: "Asia", flag: "🇶🇦", avg_temp_celsius: 27, income_tax_rate: 0, rent_1bed_usd: 1650, safety_index: 86, healthcare_index: 73 },
  { name: "Manama", country: "Bahrain", continent: "Asia", flag: "🇧🇭", avg_temp_celsius: 26, income_tax_rate: 0, rent_1bed_usd: 1100, safety_index: 82, healthcare_index: 70 },
  { name: "Kuwait City", country: "Kuwait", continent: "Asia", flag: "🇰🇼", avg_temp_celsius: 26, income_tax_rate: 0, rent_1bed_usd: 1400, safety_index: 78, healthcare_index: 68 },
  { name: "Muscat", country: "Oman", continent: "Asia", flag: "🇴🇲", avg_temp_celsius: 27, income_tax_rate: 0, rent_1bed_usd: 950, safety_index: 80, healthcare_index: 66 },
  { name: "Riyadh", country: "Saudi Arabia", continent: "Asia", flag: "🇸🇦", avg_temp_celsius: 26, income_tax_rate: 0, rent_1bed_usd: 900, safety_index: 72, healthcare_index: 64 },
  { name: "Jeddah", country: "Saudi Arabia", continent: "Asia", flag: "🇸🇦", avg_temp_celsius: 27, income_tax_rate: 0, rent_1bed_usd: 850, safety_index: 70, healthcare_index: 62 },
  { name: "Tel Aviv", country: "Israel", continent: "Asia", flag: "🇮🇱", avg_temp_celsius: 20, income_tax_rate: 37, rent_1bed_usd: 2100, safety_index: 68, healthcare_index: 78 },
  { name: "Jerusalem", country: "Israel", continent: "Asia", flag: "🇮🇱", avg_temp_celsius: 18, income_tax_rate: 37, rent_1bed_usd: 1800, safety_index: 70, healthcare_index: 76 },
  { name: "Beirut", country: "Lebanon", continent: "Asia", flag: "🇱🇧", avg_temp_celsius: 21, income_tax_rate: 25, rent_1bed_usd: 800, safety_index: 48, healthcare_index: 58 },
  { name: "Amman", country: "Jordan", continent: "Asia", flag: "🇯🇴", avg_temp_celsius: 16, income_tax_rate: 20, rent_1bed_usd: 550, safety_index: 62, healthcare_index: 60 },
  { name: "Cairo", country: "Egypt", continent: "Africa", flag: "🇪🇬", avg_temp_celsius: 22, income_tax_rate: 25, rent_1bed_usd: 400, safety_index: 42, healthcare_index: 52 },
  { name: "Casablanca", country: "Morocco", continent: "Africa", flag: "🇲🇦", avg_temp_celsius: 18, income_tax_rate: 38, rent_1bed_usd: 480, safety_index: 52, healthcare_index: 55 },
  { name: "Marrakech", country: "Morocco", continent: "Africa", flag: "🇲🇦", avg_temp_celsius: 20, income_tax_rate: 38, rent_1bed_usd: 420, safety_index: 50, healthcare_index: 52 },
  { name: "Tunis", country: "Tunisia", continent: "Africa", flag: "🇹🇳", avg_temp_celsius: 19, income_tax_rate: 35, rent_1bed_usd: 380, safety_index: 52, healthcare_index: 58 },
  { name: "Lagos", country: "Nigeria", continent: "Africa", flag: "🇳🇬", avg_temp_celsius: 27, income_tax_rate: 24, rent_1bed_usd: 650, safety_index: 28, healthcare_index: 38 },
  { name: "Nairobi", country: "Kenya", continent: "Africa", flag: "🇰🇪", avg_temp_celsius: 19, income_tax_rate: 30, rent_1bed_usd: 550, safety_index: 38, healthcare_index: 48 },
  { name: "Johannesburg", country: "South Africa", continent: "Africa", flag: "🇿🇦", avg_temp_celsius: 16, income_tax_rate: 36, rent_1bed_usd: 650, safety_index: 24, healthcare_index: 62 },
  { name: "Cape Town", country: "South Africa", continent: "Africa", flag: "🇿🇦", avg_temp_celsius: 16, income_tax_rate: 36, rent_1bed_usd: 750, safety_index: 32, healthcare_index: 68 },
  { name: "Durban", country: "South Africa", continent: "Africa", flag: "🇿🇦", avg_temp_celsius: 21, income_tax_rate: 36, rent_1bed_usd: 500, safety_index: 35, healthcare_index: 64 },
  { name: "Dar es Salaam", country: "Tanzania", continent: "Africa", flag: "🇹🇿", avg_temp_celsius: 25, income_tax_rate: 30, rent_1bed_usd: 380, safety_index: 40, healthcare_index: 45 },
  { name: "Addis Ababa", country: "Ethiopia", continent: "Africa", flag: "🇪🇹", avg_temp_celsius: 16, income_tax_rate: 35, rent_1bed_usd: 320, safety_index: 42, healthcare_index: 42 },
  { name: "Panama City", country: "Panama", continent: "Americas", flag: "🇵🇦", avg_temp_celsius: 27, income_tax_rate: 0, rent_1bed_usd: 950, safety_index: 58, healthcare_index: 64 },
  { name: "San Jose", country: "Costa Rica", continent: "Americas", flag: "🇨🇷", avg_temp_celsius: 22, income_tax_rate: 15, rent_1bed_usd: 650, safety_index: 58, healthcare_index: 70 },
  { name: "Guatemala City", country: "Guatemala", continent: "Americas", flag: "🇬🇹", avg_temp_celsius: 17, income_tax_rate: 7, rent_1bed_usd: 450, safety_index: 42, healthcare_index: 52 },
  { name: "San Salvador", country: "El Salvador", continent: "Americas", flag: "🇸🇻", avg_temp_celsius: 23, income_tax_rate: 30, rent_1bed_usd: 480, safety_index: 35, healthcare_index: 48 },
  { name: "Tegucigalpa", country: "Honduras", continent: "Americas", flag: "🇭🇳", avg_temp_celsius: 20, income_tax_rate: 25, rent_1bed_usd: 400, safety_index: 32, healthcare_index: 45 },
  { name: "Managua", country: "Nicaragua", continent: "Americas", flag: "🇳🇮", avg_temp_celsius: 26, income_tax_rate: 30, rent_1bed_usd: 380, safety_index: 45, healthcare_index: 48 },
  { name: "San Juan", country: "Puerto Rico", continent: "Americas", flag: "🇵🇷", avg_temp_celsius: 26, income_tax_rate: 33, rent_1bed_usd: 1200, safety_index: 32, healthcare_index: 68 },
  { name: "Kingston", country: "Jamaica", continent: "Americas", flag: "🇯🇲", avg_temp_celsius: 26, income_tax_rate: 25, rent_1bed_usd: 700, safety_index: 32, healthcare_index: 55 },
  { name: "Havana", country: "Cuba", continent: "Americas", flag: "🇨🇺", avg_temp_celsius: 25, income_tax_rate: 15, rent_1bed_usd: 350, safety_index: 68, healthcare_index: 72 },
  { name: "Santo Domingo", country: "Dominican Republic", continent: "Americas", flag: "🇩🇴", avg_temp_celsius: 25, income_tax_rate: 25, rent_1bed_usd: 650, safety_index: 38, healthcare_index: 58 },
  { name: "Mexico City", country: "Mexico", continent: "Americas", flag: "🇲🇽", avg_temp_celsius: 16, income_tax_rate: 30, rent_1bed_usd: 750, safety_index: 38, healthcare_index: 62 },
  { name: "Guadalajara", country: "Mexico", continent: "Americas", flag: "🇲🇽", avg_temp_celsius: 20, income_tax_rate: 30, rent_1bed_usd: 500, safety_index: 42, healthcare_index: 64 },
  { name: "Monterrey", country: "Mexico", continent: "Americas", flag: "🇲🇽", avg_temp_celsius: 22, income_tax_rate: 30, rent_1bed_usd: 550, safety_index: 40, healthcare_index: 62 },
  { name: "Cancun", country: "Mexico", continent: "Americas", flag: "🇲🇽", avg_temp_celsius: 26, income_tax_rate: 30, rent_1bed_usd: 800, safety_index: 52, healthcare_index: 66 },
  { name: "Playa del Carmen", country: "Mexico", continent: "Americas", flag: "🇲🇽", avg_temp_celsius: 27, income_tax_rate: 30, rent_1bed_usd: 850, safety_index: 48, healthcare_index: 60 },
  { name: "Merida", country: "Mexico", continent: "Americas", flag: "🇲🇽", avg_temp_celsius: 26, income_tax_rate: 30, rent_1bed_usd: 550, safety_index: 62, healthcare_index: 64 },
  { name: "Bogota", country: "Colombia", continent: "Americas", flag: "🇨🇴", avg_temp_celsius: 14, income_tax_rate: 35, rent_1bed_usd: 450, safety_index: 38, healthcare_index: 68 },
  { name: "Medellin", country: "Colombia", continent: "Americas", flag: "🇨🇴", avg_temp_celsius: 22, income_tax_rate: 35, rent_1bed_usd: 500, safety_index: 42, healthcare_index: 70 },
  { name: "Cali", country: "Colombia", continent: "Americas", flag: "🇨🇴", avg_temp_celsius: 24, income_tax_rate: 35, rent_1bed_usd: 380, safety_index: 28, healthcare_index: 58 },
  { name: "Cartagena", country: "Colombia", continent: "Americas", flag: "🇨🇴", avg_temp_celsius: 28, income_tax_rate: 35, rent_1bed_usd: 550, safety_index: 44, healthcare_index: 58 },
  { name: "Barranquilla", country: "Colombia", continent: "Americas", flag: "🇨🇴", avg_temp_celsius: 27, income_tax_rate: 35, rent_1bed_usd: 420, safety_index: 35, healthcare_index: 56 },
  { name: "Lima", country: "Peru", continent: "Americas", flag: "🇵🇪", avg_temp_celsius: 19, income_tax_rate: 30, rent_1bed_usd: 600, safety_index: 38, healthcare_index: 62 },
  { name: "Cusco", country: "Peru", continent: "Americas", flag: "🇵🇪", avg_temp_celsius: 12, income_tax_rate: 30, rent_1bed_usd: 350, safety_index: 62, healthcare_index: 58 },
  { name: "Quito", country: "Ecuador", continent: "Americas", flag: "🇪🇨", avg_temp_celsius: 15, income_tax_rate: 25, rent_1bed_usd: 450, safety_index: 45, healthcare_index: 62 },
  { name: "Guayaquil", country: "Ecuador", continent: "Americas", flag: "🇪🇨", avg_temp_celsius: 26, income_tax_rate: 25, rent_1bed_usd: 420, safety_index: 28, healthcare_index: 58 },
  { name: "La Paz", country: "Bolivia", continent: "Americas", flag: "🇧🇴", avg_temp_celsius: 8, income_tax_rate: 13, rent_1bed_usd: 350, safety_index: 48, healthcare_index: 52 },
  { name: "Santa Cruz de la Sierra", country: "Bolivia", continent: "Americas", flag: "🇧🇴", avg_temp_celsius: 23, income_tax_rate: 13, rent_1bed_usd: 400, safety_index: 40, healthcare_index: 50 },
  { name: "Santiago", country: "Chile", continent: "Americas", flag: "🇨🇱", avg_temp_celsius: 14, income_tax_rate: 40, rent_1bed_usd: 700, safety_index: 52, healthcare_index: 74 },
  { name: "Valparaiso", country: "Chile", continent: "Americas", flag: "🇨🇱", avg_temp_celsius: 14, income_tax_rate: 40, rent_1bed_usd: 480, safety_index: 50, healthcare_index: 70 },
  { name: "Buenos Aires", country: "Argentina", continent: "Americas", flag: "🇦🇷", avg_temp_celsius: 16, income_tax_rate: 35, rent_1bed_usd: 650, safety_index: 48, healthcare_index: 76 },
  { name: "Cordoba", country: "Argentina", continent: "Americas", flag: "🇦🇷", avg_temp_celsius: 18, income_tax_rate: 35, rent_1bed_usd: 380, safety_index: 52, healthcare_index: 70 },
  { name: "Mendoza", country: "Argentina", continent: "Americas", flag: "🇦🇷", avg_temp_celsius: 15, income_tax_rate: 35, rent_1bed_usd: 350, safety_index: 60, healthcare_index: 68 },
  { name: "Montevideo", country: "Uruguay", continent: "Americas", flag: "🇺🇾", avg_temp_celsius: 16, income_tax_rate: 36, rent_1bed_usd: 650, safety_index: 52, healthcare_index: 76 },
  { name: "Asuncion", country: "Paraguay", continent: "Americas", flag: "🇵🇾", avg_temp_celsius: 22, income_tax_rate: 10, rent_1bed_usd: 380, safety_index: 48, healthcare_index: 55 },
  { name: "Sao Paulo", country: "Brazil", continent: "Americas", flag: "🇧🇷", avg_temp_celsius: 20, income_tax_rate: 27, rent_1bed_usd: 900, safety_index: 32, healthcare_index: 68 },
  { name: "Rio de Janeiro", country: "Brazil", continent: "Americas", flag: "🇧🇷", avg_temp_celsius: 23, income_tax_rate: 27, rent_1bed_usd: 750, safety_index: 28, healthcare_index: 64 },
  { name: "Brasilia", country: "Brazil", continent: "Americas", flag: "🇧🇷", avg_temp_celsius: 21, income_tax_rate: 27, rent_1bed_usd: 550, safety_index: 35, healthcare_index: 72 },
  { name: "Belo Horizonte", country: "Brazil", continent: "Americas", flag: "🇧🇷", avg_temp_celsius: 21, income_tax_rate: 27, rent_1bed_usd: 420, safety_index: 28, healthcare_index: 66 },
  { name: "Curitiba", country: "Brazil", continent: "Americas", flag: "🇧🇷", avg_temp_celsius: 17, income_tax_rate: 27, rent_1bed_usd: 480, safety_index: 48, healthcare_index: 72 },
  { name: "Porto Alegre", country: "Brazil", continent: "Americas", flag: "🇧🇷", avg_temp_celsius: 19, income_tax_rate: 27, rent_1bed_usd: 450, safety_index: 32, healthcare_index: 70 },
  { name: "Recife", country: "Brazil", continent: "Americas", flag: "🇧🇷", avg_temp_celsius: 26, income_tax_rate: 27, rent_1bed_usd: 400, safety_index: 22, healthcare_index: 58 },
  { name: "Fortaleza", country: "Brazil", continent: "Americas", flag: "🇧🇷", avg_temp_celsius: 27, income_tax_rate: 27, rent_1bed_usd: 380, safety_index: 35, healthcare_index: 56 },
  { name: "Salvador", country: "Brazil", continent: "Americas", flag: "🇧🇷", avg_temp_celsius: 25, income_tax_rate: 27, rent_1bed_usd: 450, safety_index: 24, healthcare_index: 54 },
  { name: "New York", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 13, income_tax_rate: 37, rent_1bed_usd: 4200, safety_index: 45, healthcare_index: 75 },
  { name: "Los Angeles", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 18, income_tax_rate: 37, rent_1bed_usd: 2800, safety_index: 48, healthcare_index: 78 },
  { name: "San Francisco", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 14, income_tax_rate: 37, rent_1bed_usd: 3500, safety_index: 42, healthcare_index: 82 },
  { name: "Miami", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 25, income_tax_rate: 32, rent_1bed_usd: 2200, safety_index: 52, healthcare_index: 74 },
  { name: "Chicago", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 10, income_tax_rate: 37, rent_1bed_usd: 2000, safety_index: 38, healthcare_index: 78 },
  { name: "Austin", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 21, income_tax_rate: 32, rent_1bed_usd: 1600, safety_index: 58, healthcare_index: 72 },
  { name: "Denver", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 10, income_tax_rate: 32, rent_1bed_usd: 1900, safety_index: 48, healthcare_index: 78 },
  { name: "Seattle", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 11, income_tax_rate: 32, rent_1bed_usd: 2300, safety_index: 42, healthcare_index: 80 },
  { name: "Boston", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 10, income_tax_rate: 32, rent_1bed_usd: 2800, safety_index: 55, healthcare_index: 82 },
  { name: "Washington DC", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 14, income_tax_rate: 32, rent_1bed_usd: 2400, safety_index: 48, healthcare_index: 80 },
  { name: "Atlanta", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 17, income_tax_rate: 32, rent_1bed_usd: 1700, safety_index: 28, healthcare_index: 76 },
  { name: "Phoenix", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 24, income_tax_rate: 32, rent_1bed_usd: 1400, safety_index: 42, healthcare_index: 72 },
  { name: "Las Vegas", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 21, income_tax_rate: 32, rent_1bed_usd: 1200, safety_index: 42, healthcare_index: 70 },
  { name: "Dallas", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 19, income_tax_rate: 32, rent_1bed_usd: 1500, safety_index: 38, healthcare_index: 74 },
  { name: "Houston", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 21, income_tax_rate: 32, rent_1bed_usd: 1300, safety_index: 32, healthcare_index: 76 },
  { name: "Nashville", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 16, income_tax_rate: 32, rent_1bed_usd: 1600, safety_index: 42, healthcare_index: 74 },
  { name: "Portland", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 12, income_tax_rate: 32, rent_1bed_usd: 1800, safety_index: 42, healthcare_index: 78 },
  { name: "Honolulu", country: "United States", continent: "Americas", flag: "🇺🇸", avg_temp_celsius: 25, income_tax_rate: 32, rent_1bed_usd: 2200, safety_index: 58, healthcare_index: 76 },
  { name: "Toronto", country: "Canada", continent: "Americas", flag: "🇨🇦", avg_temp_celsius: 9, income_tax_rate: 33, rent_1bed_usd: 1900, safety_index: 62, healthcare_index: 80 },
  { name: "Vancouver", country: "Canada", continent: "Americas", flag: "🇨🇦", avg_temp_celsius: 11, income_tax_rate: 33, rent_1bed_usd: 2100, safety_index: 62, healthcare_index: 82 },
  { name: "Montreal", country: "Canada", continent: "Americas", flag: "🇨🇦", avg_temp_celsius: 7, income_tax_rate: 33, rent_1bed_usd: 1200, safety_index: 66, healthcare_index: 78 },
  { name: "Calgary", country: "Canada", continent: "Americas", flag: "🇨🇦", avg_temp_celsius: 4, income_tax_rate: 33, rent_1bed_usd: 1400, safety_index: 72, healthcare_index: 78 },
  { name: "Ottawa", country: "Canada", continent: "Americas", flag: "🇨🇦", avg_temp_celsius: 6, income_tax_rate: 33, rent_1bed_usd: 1500, safety_index: 78, healthcare_index: 80 },
  { name: "Quebec City", country: "Canada", continent: "Americas", flag: "🇨🇦", avg_temp_celsius: 5, income_tax_rate: 33, rent_1bed_usd: 900, safety_index: 78, healthcare_index: 76 },
  { name: "Edmonton", country: "Canada", continent: "Americas", flag: "🇨🇦", avg_temp_celsius: 2, income_tax_rate: 33, rent_1bed_usd: 1200, safety_index: 58, healthcare_index: 76 },
  { name: "London", country: "United Kingdom", continent: "Europe", flag: "🇬🇧", avg_temp_celsius: 11, income_tax_rate: 40, rent_1bed_usd: 2100, safety_index: 52, healthcare_index: 80 },
  { name: "Manchester", country: "United Kingdom", continent: "Europe", flag: "🇬🇧", avg_temp_celsius: 10, income_tax_rate: 40, rent_1bed_usd: 1200, safety_index: 48, healthcare_index: 78 },
  { name: "Edinburgh", country: "United Kingdom", continent: "Europe", flag: "🇬🇧", avg_temp_celsius: 9, income_tax_rate: 40, rent_1bed_usd: 1250, safety_index: 62, healthcare_index: 80 },
  { name: "Birmingham", country: "United Kingdom", continent: "Europe", flag: "🇬🇧", avg_temp_celsius: 10, income_tax_rate: 40, rent_1bed_usd: 1050, safety_index: 48, healthcare_index: 76 },
  { name: "Glasgow", country: "United Kingdom", continent: "Europe", flag: "🇬🇧", avg_temp_celsius: 9, income_tax_rate: 40, rent_1bed_usd: 1000, safety_index: 42, healthcare_index: 76 },
  { name: "Dublin", country: "Ireland", continent: "Europe", flag: "🇮🇪", avg_temp_celsius: 10, income_tax_rate: 40, rent_1bed_usd: 2200, safety_index: 55, healthcare_index: 78 },
  { name: "Cork", country: "Ireland", continent: "Europe", flag: "🇮🇪", avg_temp_celsius: 10, income_tax_rate: 40, rent_1bed_usd: 1400, safety_index: 62, healthcare_index: 76 },
  { name: "Paris", country: "France", continent: "Europe", flag: "🇫🇷", avg_temp_celsius: 12, income_tax_rate: 30, rent_1bed_usd: 1650, safety_index: 54, healthcare_index: 82 },
  { name: "Lyon", country: "France", continent: "Europe", flag: "🇫🇷", avg_temp_celsius: 12, income_tax_rate: 30, rent_1bed_usd: 880, safety_index: 58, healthcare_index: 80 },
  { name: "Marseille", country: "France", continent: "Europe", flag: "🇫🇷", avg_temp_celsius: 15, income_tax_rate: 30, rent_1bed_usd: 750, safety_index: 42, healthcare_index: 76 },
  { name: "Nice", country: "France", continent: "Europe", flag: "🇫🇷", avg_temp_celsius: 16, income_tax_rate: 30, rent_1bed_usd: 1200, safety_index: 52, healthcare_index: 78 },
  { name: "Toulouse", country: "France", continent: "Europe", flag: "🇫🇷", avg_temp_celsius: 13, income_tax_rate: 30, rent_1bed_usd: 780, safety_index: 62, healthcare_index: 76 },
  { name: "Berlin", country: "Germany", continent: "Europe", flag: "🇩🇪", avg_temp_celsius: 10, income_tax_rate: 42, rent_1bed_usd: 1100, safety_index: 62, healthcare_index: 80 },
  { name: "Munich", country: "Germany", continent: "Europe", flag: "🇩🇪", avg_temp_celsius: 9, income_tax_rate: 42, rent_1bed_usd: 1450, safety_index: 78, healthcare_index: 82 },
  { name: "Hamburg", country: "Germany", continent: "Europe", flag: "🇩🇪", avg_temp_celsius: 9, income_tax_rate: 42, rent_1bed_usd: 1050, safety_index: 68, healthcare_index: 80 },
  { name: "Frankfurt", country: "Germany", continent: "Europe", flag: "🇩🇪", avg_temp_celsius: 10, income_tax_rate: 42, rent_1bed_usd: 1300, safety_index: 58, healthcare_index: 82 },
  { name: "Cologne", country: "Germany", continent: "Europe", flag: "🇩🇪", avg_temp_celsius: 10, income_tax_rate: 42, rent_1bed_usd: 1000, safety_index: 62, healthcare_index: 80 },
  { name: "Stuttgart", country: "Germany", continent: "Europe", flag: "🇩🇪", avg_temp_celsius: 10, income_tax_rate: 42, rent_1bed_usd: 1150, safety_index: 72, healthcare_index: 82 },
  { name: "Dusseldorf", country: "Germany", continent: "Europe", flag: "🇩🇪", avg_temp_celsius: 10, income_tax_rate: 42, rent_1bed_usd: 1100, safety_index: 72, healthcare_index: 80 },
  { name: "Vienna", country: "Austria", continent: "Europe", flag: "🇦🇹", avg_temp_celsius: 11, income_tax_rate: 45, rent_1bed_usd: 1050, safety_index: 82, healthcare_index: 84 },
  { name: "Zurich", country: "Switzerland", continent: "Europe", flag: "🇨🇭", avg_temp_celsius: 9, income_tax_rate: 22, rent_1bed_usd: 2200, safety_index: 82, healthcare_index: 88 },
  { name: "Geneva", country: "Switzerland", continent: "Europe", flag: "🇨🇭", avg_temp_celsius: 10, income_tax_rate: 22, rent_1bed_usd: 2100, safety_index: 78, healthcare_index: 88 },
  { name: "Basel", country: "Switzerland", continent: "Europe", flag: "🇨🇭", avg_temp_celsius: 10, income_tax_rate: 22, rent_1bed_usd: 1800, safety_index: 82, healthcare_index: 86 },
  { name: "Amsterdam", country: "Netherlands", continent: "Europe", flag: "🇳🇱", avg_temp_celsius: 10, income_tax_rate: 37, rent_1bed_usd: 1750, safety_index: 58, healthcare_index: 82 },
  { name: "Rotterdam", country: "Netherlands", continent: "Europe", flag: "🇳🇱", avg_temp_celsius: 10, income_tax_rate: 37, rent_1bed_usd: 1300, safety_index: 58, healthcare_index: 80 },
  { name: "The Hague", country: "Netherlands", continent: "Europe", flag: "🇳🇱", avg_temp_celsius: 10, income_tax_rate: 37, rent_1bed_usd: 1250, safety_index: 62, healthcare_index: 80 },
  { name: "Brussels", country: "Belgium", continent: "Europe", flag: "🇧🇪", avg_temp_celsius: 10, income_tax_rate: 40, rent_1bed_usd: 1150, safety_index: 48, healthcare_index: 80 },
  { name: "Antwerp", country: "Belgium", continent: "Europe", flag: "🇧🇪", avg_temp_celsius: 10, income_tax_rate: 40, rent_1bed_usd: 950, safety_index: 52, healthcare_index: 78 },
  { name: "Luxembourg", country: "Luxembourg", continent: "Europe", flag: "🇱🇺", avg_temp_celsius: 10, income_tax_rate: 42, rent_1bed_usd: 1650, safety_index: 72, healthcare_index: 82 },
  { name: "Copenhagen", country: "Denmark", continent: "Europe", flag: "🇩🇰", avg_temp_celsius: 9, income_tax_rate: 42, rent_1bed_usd: 1400, safety_index: 78, healthcare_index: 84 },
  { name: "Aarhus", country: "Denmark", continent: "Europe", flag: "🇩🇰", avg_temp_celsius: 8, income_tax_rate: 42, rent_1bed_usd: 950, safety_index: 78, healthcare_index: 80 },
  { name: "Stockholm", country: "Sweden", continent: "Europe", flag: "🇸🇪", avg_temp_celsius: 7, income_tax_rate: 52, rent_1bed_usd: 1400, safety_index: 62, healthcare_index: 82 },
  { name: "Gothenburg", country: "Sweden", continent: "Europe", flag: "🇸🇪", avg_temp_celsius: 8, income_tax_rate: 52, rent_1bed_usd: 900, safety_index: 62, healthcare_index: 80 },
  { name: "Oslo", country: "Norway", continent: "Europe", flag: "🇳🇴", avg_temp_celsius: 4, income_tax_rate: 47, rent_1bed_usd: 1500, safety_index: 78, healthcare_index: 84 },
  { name: "Bergen", country: "Norway", continent: "Europe", flag: "🇳🇴", avg_temp_celsius: 7, income_tax_rate: 47, rent_1bed_usd: 1250, safety_index: 78, healthcare_index: 80 },
  { name: "Helsinki", country: "Finland", continent: "Europe", flag: "🇫🇮", avg_temp_celsius: 5, income_tax_rate: 56, rent_1bed_usd: 1200, safety_index: 78, healthcare_index: 82 },
  { name: "Tampere", country: "Finland", continent: "Europe", flag: "🇫🇮", avg_temp_celsius: 4, income_tax_rate: 56, rent_1bed_usd: 850, safety_index: 78, healthcare_index: 78 },
  { name: "Reykjavik", country: "Iceland", continent: "Europe", flag: "🇮🇸", avg_temp_celsius: 4, income_tax_rate: 46, rent_1bed_usd: 1600, safety_index: 88, healthcare_index: 80 },
  { name: "Madrid", country: "Spain", continent: "Europe", flag: "🇪🇸", avg_temp_celsius: 15, income_tax_rate: 24, rent_1bed_usd: 1250, safety_index: 58, healthcare_index: 78 },
  { name: "Barcelona", country: "Spain", continent: "Europe", flag: "🇪🇸", avg_temp_celsius: 17, income_tax_rate: 24, rent_1bed_usd: 1350, safety_index: 58, healthcare_index: 78 },
  { name: "Valencia", country: "Spain", continent: "Europe", flag: "🇪🇸", avg_temp_celsius: 18, income_tax_rate: 24, rent_1bed_usd: 900, safety_index: 74, healthcare_index: 76 },
  { name: "Seville", country: "Spain", continent: "Europe", flag: "🇪🇸", avg_temp_celsius: 19, income_tax_rate: 24, rent_1bed_usd: 820, safety_index: 64, healthcare_index: 74 },
  { name: "Malaga", country: "Spain", continent: "Europe", flag: "🇪🇸", avg_temp_celsius: 19, income_tax_rate: 24, rent_1bed_usd: 850, safety_index: 68, healthcare_index: 74 },
  { name: "Bilbao", country: "Spain", continent: "Europe", flag: "🇪🇸", avg_temp_celsius: 15, income_tax_rate: 24, rent_1bed_usd: 950, safety_index: 72, healthcare_index: 78 },
  { name: "Lisbon", country: "Portugal", continent: "Europe", flag: "🇵🇹", avg_temp_celsius: 17, income_tax_rate: 20, rent_1bed_usd: 1200, safety_index: 70, healthcare_index: 74 },
  { name: "Porto", country: "Portugal", continent: "Europe", flag: "🇵🇹", avg_temp_celsius: 16, income_tax_rate: 20, rent_1bed_usd: 850, safety_index: 72, healthcare_index: 74 },
  { name: "Braga", country: "Portugal", continent: "Europe", flag: "🇵🇹", avg_temp_celsius: 15, income_tax_rate: 20, rent_1bed_usd: 650, safety_index: 74, healthcare_index: 72 },
  { name: "Faro", country: "Portugal", continent: "Europe", flag: "🇵🇹", avg_temp_celsius: 18, income_tax_rate: 20, rent_1bed_usd: 900, safety_index: 72, healthcare_index: 72 },
  { name: "Rome", country: "Italy", continent: "Europe", flag: "🇮🇹", avg_temp_celsius: 15, income_tax_rate: 43, rent_1bed_usd: 1300, safety_index: 48, healthcare_index: 78 },
  { name: "Milan", country: "Italy", continent: "Europe", flag: "🇮🇹", avg_temp_celsius: 13, income_tax_rate: 43, rent_1bed_usd: 1450, safety_index: 52, healthcare_index: 80 },
  { name: "Florence", country: "Italy", continent: "Europe", flag: "🇮🇹", avg_temp_celsius: 15, income_tax_rate: 43, rent_1bed_usd: 1100, safety_index: 62, healthcare_index: 80 },
  { name: "Naples", country: "Italy", continent: "Europe", flag: "🇮🇹", avg_temp_celsius: 16, income_tax_rate: 43, rent_1bed_usd: 850, safety_index: 42, healthcare_index: 72 },
  { name: "Venice", country: "Italy", continent: "Europe", flag: "🇮🇹", avg_temp_celsius: 13, income_tax_rate: 43, rent_1bed_usd: 1200, safety_index: 58, healthcare_index: 78 },
  { name: "Turin", country: "Italy", continent: "Europe", flag: "🇮🇹", avg_temp_celsius: 12, income_tax_rate: 43, rent_1bed_usd: 850, safety_index: 62, healthcare_index: 78 },
  { name: "Palermo", country: "Italy", continent: "Europe", flag: "🇮🇹", avg_temp_celsius: 19, income_tax_rate: 43, rent_1bed_usd: 600, safety_index: 42, healthcare_index: 68 },
  { name: "Athens", country: "Greece", continent: "Europe", flag: "🇬🇷", avg_temp_celsius: 18, income_tax_rate: 44, rent_1bed_usd: 700, safety_index: 60, healthcare_index: 68 },
  { name: "Thessaloniki", country: "Greece", continent: "Europe", flag: "🇬🇷", avg_temp_celsius: 16, income_tax_rate: 44, rent_1bed_usd: 520, safety_index: 58, healthcare_index: 66 },
  { name: "Limassol", country: "Cyprus", continent: "Europe", flag: "🇨🇾", avg_temp_celsius: 21, income_tax_rate: 20, rent_1bed_usd: 950, safety_index: 70, healthcare_index: 72 },
  { name: "Warsaw", country: "Poland", continent: "Europe", flag: "🇵🇱", avg_temp_celsius: 9, income_tax_rate: 32, rent_1bed_usd: 750, safety_index: 68, healthcare_index: 70 },
  { name: "Krakow", country: "Poland", continent: "Europe", flag: "🇵🇱", avg_temp_celsius: 8, income_tax_rate: 32, rent_1bed_usd: 650, safety_index: 72, healthcare_index: 72 },
  { name: "Wroclaw", country: "Poland", continent: "Europe", flag: "🇵🇱", avg_temp_celsius: 9, income_tax_rate: 32, rent_1bed_usd: 600, safety_index: 72, healthcare_index: 70 },
  { name: "Gdansk", country: "Poland", continent: "Europe", flag: "🇵🇱", avg_temp_celsius: 8, income_tax_rate: 32, rent_1bed_usd: 700, safety_index: 75, healthcare_index: 72 },
  { name: "Prague", country: "Czech Republic", continent: "Europe", flag: "🇨🇿", avg_temp_celsius: 10, income_tax_rate: 23, rent_1bed_usd: 900, safety_index: 72, healthcare_index: 75 },
  { name: "Brno", country: "Czech Republic", continent: "Europe", flag: "🇨🇿", avg_temp_celsius: 9, income_tax_rate: 23, rent_1bed_usd: 600, safety_index: 75, healthcare_index: 72 },
  { name: "Budapest", country: "Hungary", continent: "Europe", flag: "🇭🇺", avg_temp_celsius: 12, income_tax_rate: 15, rent_1bed_usd: 650, safety_index: 66, healthcare_index: 68 },
  { name: "Ljubljana", country: "Slovenia", continent: "Europe", flag: "🇸🇮", avg_temp_celsius: 12, income_tax_rate: 25, rent_1bed_usd: 850, safety_index: 82, healthcare_index: 76 },
  { name: "Zagreb", country: "Croatia", continent: "Europe", flag: "🇭🇷", avg_temp_celsius: 13, income_tax_rate: 23, rent_1bed_usd: 700, safety_index: 72, healthcare_index: 70 },
  { name: "Split", country: "Croatia", continent: "Europe", flag: "🇭🇷", avg_temp_celsius: 16, income_tax_rate: 23, rent_1bed_usd: 800, safety_index: 72, healthcare_index: 68 },
  { name: "Belgrade", country: "Serbia", continent: "Europe", flag: "🇷🇸", avg_temp_celsius: 13, income_tax_rate: 20, rent_1bed_usd: 500, safety_index: 52, healthcare_index: 62 },
  { name: "Bucharest", country: "Romania", continent: "Europe", flag: "🇷🇴", avg_temp_celsius: 11, income_tax_rate: 10, rent_1bed_usd: 550, safety_index: 64, healthcare_index: 66 },
  { name: "Cluj-Napoca", country: "Romania", continent: "Europe", flag: "🇷🇴", avg_temp_celsius: 10, income_tax_rate: 10, rent_1bed_usd: 480, safety_index: 70, healthcare_index: 68 },
  { name: "Sofia", country: "Bulgaria", continent: "Europe", flag: "🇧🇬", avg_temp_celsius: 11, income_tax_rate: 10, rent_1bed_usd: 480, safety_index: 66, healthcare_index: 64 },
  { name: "Plovdiv", country: "Bulgaria", continent: "Europe", flag: "🇧🇬", avg_temp_celsius: 13, income_tax_rate: 10, rent_1bed_usd: 380, safety_index: 68, healthcare_index: 62 },
  { name: "Tallinn", country: "Estonia", continent: "Europe", flag: "🇪🇪", avg_temp_celsius: 6, income_tax_rate: 20, rent_1bed_usd: 800, safety_index: 78, healthcare_index: 75 },
  { name: "Riga", country: "Latvia", continent: "Europe", flag: "🇱🇻", avg_temp_celsius: 6, income_tax_rate: 20, rent_1bed_usd: 650, safety_index: 62, healthcare_index: 70 },
  { name: "Vilnius", country: "Lithuania", continent: "Europe", flag: "🇱🇹", avg_temp_celsius: 7, income_tax_rate: 20, rent_1bed_usd: 750, safety_index: 68, healthcare_index: 72 },
  { name: "Kyiv", country: "Ukraine", continent: "Europe", flag: "🇺🇦", avg_temp_celsius: 8, income_tax_rate: 18, rent_1bed_usd: 550, safety_index: 42, healthcare_index: 58 },
  { name: "Lviv", country: "Ukraine", continent: "Europe", flag: "🇺🇦", avg_temp_celsius: 8, income_tax_rate: 18, rent_1bed_usd: 420, safety_index: 62, healthcare_index: 60 },
  { name: "Moscow", country: "Russia", continent: "Europe", flag: "🇷🇺", avg_temp_celsius: 6, income_tax_rate: 13, rent_1bed_usd: 1100, safety_index: 38, healthcare_index: 68 },
  { name: "Saint Petersburg", country: "Russia", continent: "Europe", flag: "🇷🇺", avg_temp_celsius: 6, income_tax_rate: 13, rent_1bed_usd: 800, safety_index: 42, healthcare_index: 72 },
  { name: "Kazan", country: "Russia", continent: "Europe", flag: "🇷🇺", avg_temp_celsius: 5, income_tax_rate: 13, rent_1bed_usd: 450, safety_index: 58, healthcare_index: 66 },
  { name: "Yekaterinburg", country: "Russia", continent: "Europe", flag: "🇷🇺", avg_temp_celsius: 4, income_tax_rate: 13, rent_1bed_usd: 420, safety_index: 52, healthcare_index: 64 },
  { name: "Novosibirsk", country: "Russia", continent: "Europe", flag: "🇷🇺", avg_temp_celsius: 2, income_tax_rate: 13, rent_1bed_usd: 380, safety_index: 58, healthcare_index: 62 },
  { name: "Tbilisi", country: "Georgia", continent: "Asia", flag: "🇬🇪", avg_temp_celsius: 13, income_tax_rate: 1, rent_1bed_usd: 550, safety_index: 72, healthcare_index: 58 },
  { name: "Batumi", country: "Georgia", continent: "Asia", flag: "🇬🇪", avg_temp_celsius: 19, income_tax_rate: 1, rent_1bed_usd: 420, safety_index: 70, healthcare_index: 56 },
  { name: "Yerevan", country: "Armenia", continent: "Asia", flag: "🇦🇲", avg_temp_celsius: 13, income_tax_rate: 20, rent_1bed_usd: 450, safety_index: 68, healthcare_index: 60 },
  { name: "Baku", country: "Azerbaijan", continent: "Asia", flag: "🇦🇿", avg_temp_celsius: 15, income_tax_rate: 20, rent_1bed_usd: 650, safety_index: 65, healthcare_index: 62 },
  { name: "Almaty", country: "Kazakhstan", continent: "Asia", flag: "🇰🇿", avg_temp_celsius: 11, income_tax_rate: 10, rent_1bed_usd: 550, safety_index: 58, healthcare_index: 62 },
  { name: "Astana", country: "Kazakhstan", continent: "Asia", flag: "🇰🇿", avg_temp_celsius: 5, income_tax_rate: 10, rent_1bed_usd: 500, safety_index: 68, healthcare_index: 60 },
  { name: "Tashkent", country: "Uzbekistan", continent: "Asia", flag: "🇺🇿", avg_temp_celsius: 15, income_tax_rate: 12, rent_1bed_usd: 350, safety_index: 62, healthcare_index: 55 },
  { name: "Bangkok", country: "Thailand", continent: "Asia", flag: "🇹🇭", avg_temp_celsius: 29, income_tax_rate: 15, rent_1bed_usd: 650, safety_index: 62, healthcare_index: 78 },
  { name: "Chiang Mai", country: "Thailand", continent: "Asia", flag: "🇹🇭", avg_temp_celsius: 26, income_tax_rate: 15, rent_1bed_usd: 420, safety_index: 68, healthcare_index: 70 },
  { name: "Phuket", country: "Thailand", continent: "Asia", flag: "🇹🇭", avg_temp_celsius: 28, income_tax_rate: 15, rent_1bed_usd: 520, safety_index: 58, healthcare_index: 68 },
  { name: "Singapore", country: "Singapore", continent: "Asia", flag: "🇸🇬", avg_temp_celsius: 27, income_tax_rate: 22, rent_1bed_usd: 2800, safety_index: 86, healthcare_index: 88 },
  { name: "Kuala Lumpur", country: "Malaysia", continent: "Asia", flag: "🇲🇾", avg_temp_celsius: 27, income_tax_rate: 24, rent_1bed_usd: 550, safety_index: 58, healthcare_index: 76 },
  { name: "Penang", country: "Malaysia", continent: "Asia", flag: "🇲🇾", avg_temp_celsius: 27, income_tax_rate: 24, rent_1bed_usd: 480, safety_index: 65, healthcare_index: 74 },
  { name: "Jakarta", country: "Indonesia", continent: "Asia", flag: "🇮🇩", avg_temp_celsius: 27, income_tax_rate: 25, rent_1bed_usd: 550, safety_index: 48, healthcare_index: 54 },
  { name: "Bali", country: "Indonesia", continent: "Asia", flag: "🇮🇩", avg_temp_celsius: 27, income_tax_rate: 15, rent_1bed_usd: 550, safety_index: 56, healthcare_index: 54 },
  { name: "Surabaya", country: "Indonesia", continent: "Asia", flag: "🇮🇩", avg_temp_celsius: 28, income_tax_rate: 25, rent_1bed_usd: 380, safety_index: 48, healthcare_index: 52 },
  { name: "Ho Chi Minh City", country: "Vietnam", continent: "Asia", flag: "🇻🇳", avg_temp_celsius: 28, income_tax_rate: 20, rent_1bed_usd: 500, safety_index: 52, healthcare_index: 58 },
  { name: "Hanoi", country: "Vietnam", continent: "Asia", flag: "🇻🇳", avg_temp_celsius: 24, income_tax_rate: 20, rent_1bed_usd: 450, safety_index: 58, healthcare_index: 60 },
  { name: "Manila", country: "Philippines", continent: "Asia", flag: "🇵🇭", avg_temp_celsius: 27, income_tax_rate: 25, rent_1bed_usd: 450, safety_index: 38, healthcare_index: 58 },
  { name: "Cebu", country: "Philippines", continent: "Asia", flag: "🇵🇭", avg_temp_celsius: 28, income_tax_rate: 25, rent_1bed_usd: 380, safety_index: 48, healthcare_index: 56 },
  { name: "Taipei", country: "Taiwan", continent: "Asia", flag: "🇹🇼", avg_temp_celsius: 23, income_tax_rate: 20, rent_1bed_usd: 750, safety_index: 78, healthcare_index: 82 },
  { name: "Kaohsiung", country: "Taiwan", continent: "Asia", flag: "🇹🇼", avg_temp_celsius: 25, income_tax_rate: 20, rent_1bed_usd: 520, safety_index: 72, healthcare_index: 78 },
  { name: "Tokyo", country: "Japan", continent: "Asia", flag: "🇯🇵", avg_temp_celsius: 16, income_tax_rate: 33, rent_1bed_usd: 1200, safety_index: 80, healthcare_index: 86 },
  { name: "Osaka", country: "Japan", continent: "Asia", flag: "🇯🇵", avg_temp_celsius: 16, income_tax_rate: 33, rent_1bed_usd: 850, safety_index: 78, healthcare_index: 84 },
  { name: "Kyoto", country: "Japan", continent: "Asia", flag: "🇯🇵", avg_temp_celsius: 15, income_tax_rate: 33, rent_1bed_usd: 720, safety_index: 82, healthcare_index: 82 },
  { name: "Fukuoka", country: "Japan", continent: "Asia", flag: "🇯🇵", avg_temp_celsius: 17, income_tax_rate: 33, rent_1bed_usd: 680, safety_index: 78, healthcare_index: 82 },
]

/** Exactly 200 cities for the recommendation engine */
export const CITY_DATABASE = CITIES
