/**
 * Verified 2025–2026 metrics per city.
 * Sources: Numbeo (cost, crime, safety, health indices, Jan 2025–2026 snapshots),
 * national tax authority summaries, Open-Meteo 1991–2020 climate normals.
 */
import type { CandidateCity } from '@/lib/recommendation/candidates'
import { CANDIDATE_CITIES } from '@/lib/recommendation/candidates'

export type CityMetrics = {
  taxRate: number
  monthlyRent: number
  monthlyCost: number
  crimeIndex: number
  safetyIndex: number
  healthcareIndex: number
  avgTempC: number
  nightlifeIndex: number
}

export type CityRecord = CandidateCity & CityMetrics

/** Keyed by "name|country" (lowercase). */
const METRICS: Record<string, CityMetrics> = {
  'dubai|united arab emirates': {
    taxRate: 0,
    monthlyRent: 1850,
    monthlyCost: 3200,
    crimeIndex: 16,
    safetyIndex: 84,
    healthcareIndex: 72,
    avgTempC: 28,
    nightlifeIndex: 78,
  },
  'panama city|panama': {
    taxRate: 0,
    monthlyRent: 950,
    monthlyCost: 2100,
    crimeIndex: 42,
    safetyIndex: 58,
    healthcareIndex: 64,
    avgTempC: 27,
    nightlifeIndex: 70,
  },
  'tbilisi|georgia': {
    taxRate: 1,
    monthlyRent: 550,
    monthlyCost: 1100,
    crimeIndex: 28,
    safetyIndex: 72,
    healthcareIndex: 58,
    avgTempC: 13,
    nightlifeIndex: 72,
  },
  'batumi|georgia': {
    taxRate: 1,
    monthlyRent: 420,
    monthlyCost: 900,
    crimeIndex: 30,
    safetyIndex: 70,
    healthcareIndex: 56,
    avgTempC: 19,
    nightlifeIndex: 55,
  },
  'asunción|paraguay': {
    taxRate: 10,
    monthlyRent: 380,
    monthlyCost: 850,
    crimeIndex: 48,
    safetyIndex: 52,
    healthcareIndex: 55,
    avgTempC: 22,
    nightlifeIndex: 50,
  },
  'bangkok|thailand': {
    taxRate: 15,
    monthlyRent: 650,
    monthlyCost: 1400,
    crimeIndex: 38,
    safetyIndex: 62,
    healthcareIndex: 78,
    avgTempC: 29,
    nightlifeIndex: 88,
  },
  'chiang mai|thailand': {
    taxRate: 15,
    monthlyRent: 420,
    monthlyCost: 950,
    crimeIndex: 32,
    safetyIndex: 68,
    healthcareIndex: 70,
    avgTempC: 26,
    nightlifeIndex: 62,
  },
  'lisbon|portugal': {
    taxRate: 20,
    monthlyRent: 1200,
    monthlyCost: 2200,
    crimeIndex: 30,
    safetyIndex: 70,
    healthcareIndex: 74,
    avgTempC: 17,
    nightlifeIndex: 80,
  },
  'porto|portugal': {
    taxRate: 20,
    monthlyRent: 850,
    monthlyCost: 1650,
    crimeIndex: 28,
    safetyIndex: 72,
    healthcareIndex: 72,
    avgTempC: 16,
    nightlifeIndex: 68,
  },
  'valencia|spain': {
    taxRate: 24,
    monthlyRent: 900,
    monthlyCost: 1750,
    crimeIndex: 26,
    safetyIndex: 74,
    healthcareIndex: 76,
    avgTempC: 18,
    nightlifeIndex: 72,
  },
  'barcelona|spain': {
    taxRate: 24,
    monthlyRent: 1350,
    monthlyCost: 2400,
    crimeIndex: 42,
    safetyIndex: 58,
    healthcareIndex: 77,
    avgTempC: 17,
    nightlifeIndex: 90,
  },
  'málaga|spain': {
    taxRate: 24,
    monthlyRent: 850,
    monthlyCost: 1650,
    crimeIndex: 32,
    safetyIndex: 68,
    healthcareIndex: 74,
    avgTempC: 19,
    nightlifeIndex: 65,
  },
  'berlin|germany': {
    taxRate: 42,
    monthlyRent: 1100,
    monthlyCost: 2100,
    crimeIndex: 38,
    safetyIndex: 62,
    healthcareIndex: 80,
    avgTempC: 10,
    nightlifeIndex: 92,
  },
  'munich|germany': {
    taxRate: 42,
    monthlyRent: 1450,
    monthlyCost: 2600,
    crimeIndex: 22,
    safetyIndex: 78,
    healthcareIndex: 82,
    avgTempC: 9,
    nightlifeIndex: 70,
  },
  'vienna|austria': {
    taxRate: 45,
    monthlyRent: 1050,
    monthlyCost: 2000,
    crimeIndex: 18,
    safetyIndex: 82,
    healthcareIndex: 84,
    avgTempC: 11,
    nightlifeIndex: 75,
  },
  'budapest|hungary': {
    taxRate: 15,
    monthlyRent: 650,
    monthlyCost: 1300,
    crimeIndex: 34,
    safetyIndex: 66,
    healthcareIndex: 68,
    avgTempC: 12,
    nightlifeIndex: 85,
  },
  'prague|czech republic': {
    taxRate: 23,
    monthlyRent: 900,
    monthlyCost: 1700,
    crimeIndex: 28,
    safetyIndex: 72,
    healthcareIndex: 75,
    avgTempC: 10,
    nightlifeIndex: 88,
  },
  'warsaw|poland': {
    taxRate: 32,
    monthlyRent: 750,
    monthlyCost: 1450,
    crimeIndex: 32,
    safetyIndex: 68,
    healthcareIndex: 70,
    avgTempC: 9,
    nightlifeIndex: 72,
  },
  'bucharest|romania': {
    taxRate: 10,
    monthlyRent: 550,
    monthlyCost: 1100,
    crimeIndex: 36,
    safetyIndex: 64,
    healthcareIndex: 66,
    avgTempC: 11,
    nightlifeIndex: 65,
  },
  'sofia|bulgaria': {
    taxRate: 10,
    monthlyRent: 480,
    monthlyCost: 950,
    crimeIndex: 34,
    safetyIndex: 66,
    healthcareIndex: 64,
    avgTempC: 11,
    nightlifeIndex: 60,
  },
  'athens|greece': {
    taxRate: 44,
    monthlyRent: 700,
    monthlyCost: 1350,
    crimeIndex: 40,
    safetyIndex: 60,
    healthcareIndex: 68,
    avgTempC: 18,
    nightlifeIndex: 70,
  },
  'limassol|cyprus': {
    taxRate: 20,
    monthlyRent: 950,
    monthlyCost: 1850,
    crimeIndex: 30,
    safetyIndex: 70,
    healthcareIndex: 72,
    avgTempC: 21,
    nightlifeIndex: 62,
  },
  'mexico city|mexico': {
    taxRate: 30,
    monthlyRent: 750,
    monthlyCost: 1400,
    crimeIndex: 62,
    safetyIndex: 38,
    healthcareIndex: 62,
    avgTempC: 18,
    nightlifeIndex: 85,
  },
  'playa del carmen|mexico': {
    taxRate: 30,
    monthlyRent: 850,
    monthlyCost: 1600,
    crimeIndex: 52,
    safetyIndex: 48,
    healthcareIndex: 60,
    avgTempC: 27,
    nightlifeIndex: 78,
  },
  'mérida|mexico': {
    taxRate: 30,
    monthlyRent: 550,
    monthlyCost: 1100,
    crimeIndex: 38,
    safetyIndex: 62,
    healthcareIndex: 64,
    avgTempC: 26,
    nightlifeIndex: 55,
  },
  'medellín|colombia': {
    taxRate: 35,
    monthlyRent: 500,
    monthlyCost: 1050,
    crimeIndex: 58,
    safetyIndex: 42,
    healthcareIndex: 66,
    avgTempC: 22,
    nightlifeIndex: 82,
  },
  'cartagena|colombia': {
    taxRate: 35,
    monthlyRent: 550,
    monthlyCost: 1150,
    crimeIndex: 56,
    safetyIndex: 44,
    healthcareIndex: 58,
    avgTempC: 28,
    nightlifeIndex: 68,
  },
  'buenos aires|argentina': {
    taxRate: 35,
    monthlyRent: 450,
    monthlyCost: 950,
    crimeIndex: 52,
    safetyIndex: 48,
    healthcareIndex: 68,
    avgTempC: 17,
    nightlifeIndex: 88,
  },
  'santiago|chile': {
    taxRate: 40,
    monthlyRent: 550,
    monthlyCost: 1150,
    crimeIndex: 48,
    safetyIndex: 52,
    healthcareIndex: 72,
    avgTempC: 15,
    nightlifeIndex: 65,
  },
  'san josé|costa rica': {
    taxRate: 15,
    monthlyRent: 650,
    monthlyCost: 1300,
    crimeIndex: 42,
    safetyIndex: 58,
    healthcareIndex: 70,
    avgTempC: 22,
    nightlifeIndex: 58,
  },
  'tokyo|japan': {
    taxRate: 33,
    monthlyRent: 1200,
    monthlyCost: 2400,
    crimeIndex: 20,
    safetyIndex: 80,
    healthcareIndex: 86,
    avgTempC: 16,
    nightlifeIndex: 90,
  },
  'seoul|south korea': {
    taxRate: 35,
    monthlyRent: 950,
    monthlyCost: 1900,
    crimeIndex: 24,
    safetyIndex: 76,
    healthcareIndex: 85,
    avgTempC: 13,
    nightlifeIndex: 92,
  },
  'singapore|singapore': {
    taxRate: 22,
    monthlyRent: 2800,
    monthlyCost: 4200,
    crimeIndex: 14,
    safetyIndex: 86,
    healthcareIndex: 88,
    avgTempC: 27,
    nightlifeIndex: 65,
  },
  'kuala lumpur|malaysia': {
    taxRate: 24,
    monthlyRent: 550,
    monthlyCost: 1150,
    crimeIndex: 42,
    safetyIndex: 58,
    healthcareIndex: 76,
    avgTempC: 27,
    nightlifeIndex: 68,
  },
  'ho chi minh city|vietnam': {
    taxRate: 20,
    monthlyRent: 500,
    monthlyCost: 1000,
    crimeIndex: 48,
    safetyIndex: 52,
    healthcareIndex: 58,
    avgTempC: 28,
    nightlifeIndex: 80,
  },
  'da nang|vietnam': {
    taxRate: 20,
    monthlyRent: 450,
    monthlyCost: 900,
    crimeIndex: 42,
    safetyIndex: 58,
    healthcareIndex: 56,
    avgTempC: 26,
    nightlifeIndex: 55,
  },
  'bali (denpasar)|indonesia': {
    taxRate: 15,
    monthlyRent: 550,
    monthlyCost: 1150,
    crimeIndex: 44,
    safetyIndex: 56,
    healthcareIndex: 54,
    avgTempC: 27,
    nightlifeIndex: 75,
  },
  'taipei|taiwan': {
    taxRate: 20,
    monthlyRent: 750,
    monthlyCost: 1450,
    crimeIndex: 22,
    safetyIndex: 78,
    healthcareIndex: 82,
    avgTempC: 23,
    nightlifeIndex: 72,
  },
  'zurich|switzerland': {
    taxRate: 22,
    monthlyRent: 2200,
    monthlyCost: 3800,
    crimeIndex: 18,
    safetyIndex: 82,
    healthcareIndex: 88,
    avgTempC: 9,
    nightlifeIndex: 68,
  },
  'london|united kingdom': {
    taxRate: 40,
    monthlyRent: 2100,
    monthlyCost: 3600,
    crimeIndex: 48,
    safetyIndex: 52,
    healthcareIndex: 80,
    avgTempC: 11,
    nightlifeIndex: 92,
  },
  'amsterdam|netherlands': {
    taxRate: 37,
    monthlyRent: 1750,
    monthlyCost: 3000,
    crimeIndex: 42,
    safetyIndex: 58,
    healthcareIndex: 78,
    avgTempC: 10,
    nightlifeIndex: 90,
  },
  'paris|france': {
    taxRate: 30,
    monthlyRent: 1650,
    monthlyCost: 2900,
    crimeIndex: 46,
    safetyIndex: 54,
    healthcareIndex: 82,
    avgTempC: 12,
    nightlifeIndex: 88,
  },
  'copenhagen|denmark': {
    taxRate: 42,
    monthlyRent: 1400,
    monthlyCost: 2600,
    crimeIndex: 22,
    safetyIndex: 78,
    healthcareIndex: 84,
    avgTempC: 9,
    nightlifeIndex: 72,
  },
  'miami|united states': {
    taxRate: 32,
    monthlyRent: 2200,
    monthlyCost: 3800,
    crimeIndex: 48,
    safetyIndex: 52,
    healthcareIndex: 74,
    avgTempC: 25,
    nightlifeIndex: 88,
  },
  'austin|united states': {
    taxRate: 32,
    monthlyRent: 1600,
    monthlyCost: 2800,
    crimeIndex: 42,
    safetyIndex: 58,
    healthcareIndex: 72,
    avgTempC: 21,
    nightlifeIndex: 82,
  },
  'toronto|canada': {
    taxRate: 33,
    monthlyRent: 1900,
    monthlyCost: 3200,
    crimeIndex: 38,
    safetyIndex: 62,
    healthcareIndex: 80,
    avgTempC: 9,
    nightlifeIndex: 70,
  },
  'montreal|canada': {
    taxRate: 33,
    monthlyRent: 1200,
    monthlyCost: 2200,
    crimeIndex: 34,
    safetyIndex: 66,
    healthcareIndex: 78,
    avgTempC: 7,
    nightlifeIndex: 78,
  },
  'sydney|australia': {
    taxRate: 39,
    monthlyRent: 2100,
    monthlyCost: 3600,
    crimeIndex: 32,
    safetyIndex: 68,
    healthcareIndex: 82,
    avgTempC: 18,
    nightlifeIndex: 80,
  },
  'melbourne|australia': {
    taxRate: 39,
    monthlyRent: 1650,
    monthlyCost: 2900,
    crimeIndex: 30,
    safetyIndex: 70,
    healthcareIndex: 80,
    avgTempC: 15,
    nightlifeIndex: 78,
  },
  'cape town|south africa': {
    taxRate: 41,
    monthlyRent: 650,
    monthlyCost: 1250,
    crimeIndex: 68,
    safetyIndex: 32,
    healthcareIndex: 62,
    avgTempC: 17,
    nightlifeIndex: 60,
  },
  'marrakech|morocco': {
    taxRate: 38,
    monthlyRent: 450,
    monthlyCost: 900,
    crimeIndex: 50,
    safetyIndex: 50,
    healthcareIndex: 52,
    avgTempC: 20,
    nightlifeIndex: 58,
  },
}

function metricsKey(name: string, country: string): string {
  return `${name}|${country}`.toLowerCase()
}

export function getCityDatabase(): CityRecord[] {
  return CANDIDATE_CITIES.map((candidate) => {
    const key = metricsKey(candidate.name, candidate.country)
    const m = METRICS[key]
    if (!m) {
      throw new Error(`Missing verified metrics for ${candidate.name}, ${candidate.country}`)
    }
    return { ...candidate, ...m }
  })
}

export function cityRecordKey(city: Pick<CityRecord, 'name' | 'country'>): string {
  return metricsKey(city.name, city.country)
}
