/**
 * Approximate effective personal income tax % for remote workers (2024–2025).
 * Sources: national revenue services, PwC summaries, territorial-tax regimes.
 */
export const COUNTRY_TAX_RATE_PERCENT: Record<string, number> = {
  'United Arab Emirates': 0,
  Panama: 0,
  Georgia: 1,
  Paraguay: 10,
  Bulgaria: 10,
  Romania: 10,
  Malaysia: 24,
  Thailand: 15,
  Indonesia: 15,
  Vietnam: 20,
  Philippines: 25,
  Portugal: 28,
  Spain: 24,
  Italy: 43,
  France: 30,
  Germany: 42,
  Netherlands: 37,
  Belgium: 40,
  Austria: 55,
  Switzerland: 22,
  'United Kingdom': 40,
  Ireland: 40,
  Poland: 32,
  'Czech Republic': 23,
  Hungary: 15,
  Croatia: 30,
  Serbia: 20,
  Greece: 44,
  Turkey: 40,
  Mexico: 30,
  Colombia: 35,
  Brazil: 27,
  Argentina: 35,
  Chile: 40,
  'Costa Rica': 15,
  'United States': 32,
  Canada: 33,
  Japan: 33,
  'South Korea': 35,
  China: 25,
  Taiwan: 20,
  Singapore: 22,
  'Hong Kong': 15,
  India: 30,
  Australia: 39,
  'New Zealand': 33,
  'South Africa': 41,
  Morocco: 38,
  Egypt: 25,
  'Saudi Arabia': 0,
  Qatar: 0,
  Bahrain: 0,
  Cyprus: 20,
  Malta: 35,
}

export function getCountryTaxRate(country: string): number {
  return COUNTRY_TAX_RATE_PERCENT[country] ?? 25
}
