export type CityData = {
  name: string
  country: string
  continent: string
  slug: string
  monthly_rent_usd: number
  safety_score: number
  weather_score: number
  internet_speed_mbps: number
  tax_rate_percent: number
  introvert_friendly: boolean
  retiree_score: number
  tags: string[]
}

export const CITIES: CityData[] = [
  {
    name: 'Lisbon',
    country: 'Portugal',
    continent: 'Europe',
    slug: 'lisbon',
    monthly_rent_usd: 1200,
    safety_score: 8,
    weather_score: 9,
    internet_speed_mbps: 450,
    tax_rate_percent: 28,
    introvert_friendly: false,
    retiree_score: 9,
    tags: ['coastal', 'culture', 'vibrant', 'remote-work'],
  },
  {
    name: 'Bangkok',
    country: 'Thailand',
    continent: 'Asia',
    slug: 'bangkok',
    monthly_rent_usd: 700,
    safety_score: 7,
    weather_score: 8,
    internet_speed_mbps: 350,
    tax_rate_percent: 0,
    introvert_friendly: false,
    retiree_score: 8,
    tags: ['food', 'urban', 'affordable', 'remote-work'],
  },
  {
    name: 'Chiang Mai',
    country: 'Thailand',
    continent: 'Asia',
    slug: 'chiang-mai',
    monthly_rent_usd: 450,
    safety_score: 8,
    weather_score: 7,
    internet_speed_mbps: 300,
    tax_rate_percent: 0,
    introvert_friendly: true,
    retiree_score: 9,
    tags: ['mountain', 'affordable', 'nomad-hub', 'food'],
  },
  {
    name: 'Tbilisi',
    country: 'Georgia',
    continent: 'Asia',
    slug: 'tbilisi',
    monthly_rent_usd: 500,
    safety_score: 8,
    weather_score: 7,
    internet_speed_mbps: 250,
    tax_rate_percent: 1,
    introvert_friendly: true,
    retiree_score: 9,
    tags: ['affordable', 'culture', 'food', 'remote-work'],
  },
  {
    name: 'Medellín',
    country: 'Colombia',
    continent: 'Latin America',
    slug: 'medellin',
    monthly_rent_usd: 650,
    safety_score: 7,
    weather_score: 9,
    internet_speed_mbps: 180,
    tax_rate_percent: 0,
    introvert_friendly: false,
    retiree_score: 9,
    tags: ['spring-weather', 'affordable', 'vibrant', 'nomad-hub'],
  },
  {
    name: 'Budapest',
    country: 'Hungary',
    continent: 'Europe',
    slug: 'budapest',
    monthly_rent_usd: 700,
    safety_score: 8,
    weather_score: 7,
    internet_speed_mbps: 380,
    tax_rate_percent: 15,
    introvert_friendly: true,
    retiree_score: 8,
    tags: ['culture', 'affordable', 'vibrant', 'walkable'],
  },
  {
    name: 'Tallinn',
    country: 'Estonia',
    continent: 'Europe',
    slug: 'tallinn',
    monthly_rent_usd: 800,
    safety_score: 9,
    weather_score: 6,
    internet_speed_mbps: 600,
    tax_rate_percent: 20,
    introvert_friendly: true,
    retiree_score: 9,
    tags: ['tech', 'remote-work', 'walkable', 'e-residency'],
  },
  {
    name: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    slug: 'bali',
    monthly_rent_usd: 700,
    safety_score: 7,
    weather_score: 9,
    internet_speed_mbps: 120,
    tax_rate_percent: 0,
    introvert_friendly: false,
    retiree_score: 9,
    tags: ['beach', 'wellness', 'nomad-hub', 'tropical'],
  },
  {
    name: 'Mexico City',
    country: 'Mexico',
    continent: 'Latin America',
    slug: 'mexico-city',
    monthly_rent_usd: 850,
    safety_score: 6,
    weather_score: 8,
    internet_speed_mbps: 200,
    tax_rate_percent: 30,
    introvert_friendly: false,
    retiree_score: 8,
    tags: ['culture', 'food', 'urban', 'remote-work'],
  },
  {
    name: 'Porto',
    country: 'Portugal',
    continent: 'Europe',
    slug: 'porto',
    monthly_rent_usd: 950,
    safety_score: 8,
    weather_score: 8,
    internet_speed_mbps: 420,
    tax_rate_percent: 28,
    introvert_friendly: true,
    retiree_score: 8,
    tags: ['coastal', 'walkable', 'wine', 'culture'],
  },
  {
    name: 'Belgrade',
    country: 'Serbia',
    continent: 'Europe',
    slug: 'belgrade',
    monthly_rent_usd: 550,
    safety_score: 7,
    weather_score: 7,
    internet_speed_mbps: 280,
    tax_rate_percent: 10,
    introvert_friendly: true,
    retiree_score: 8,
    tags: ['affordable', 'vibrant', 'culture', 'remote-work'],
  },
  {
    name: 'Plovdiv',
    country: 'Bulgaria',
    continent: 'Europe',
    slug: 'plovdiv',
    monthly_rent_usd: 400,
    safety_score: 8,
    weather_score: 7,
    internet_speed_mbps: 320,
    tax_rate_percent: 10,
    introvert_friendly: true,
    retiree_score: 7,
    tags: ['affordable', 'history', 'walkable', 'quiet'],
  },
  {
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    continent: 'Asia',
    slug: 'kuala-lumpur',
    monthly_rent_usd: 550,
    safety_score: 8,
    weather_score: 8,
    internet_speed_mbps: 350,
    tax_rate_percent: 24,
    introvert_friendly: false,
    retiree_score: 8,
    tags: ['food', 'urban', 'english-friendly', 'affordable'],
  },
  {
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    continent: 'Asia',
    slug: 'ho-chi-minh-city',
    monthly_rent_usd: 500,
    safety_score: 7,
    weather_score: 8,
    internet_speed_mbps: 180,
    tax_rate_percent: 0,
    introvert_friendly: false,
    retiree_score: 8,
    tags: ['food', 'affordable', 'urban', 'remote-work'],
  },
  {
    name: 'Buenos Aires',
    country: 'Argentina',
    continent: 'Latin America',
    slug: 'buenos-aires',
    monthly_rent_usd: 550,
    safety_score: 7,
    weather_score: 7,
    internet_speed_mbps: 150,
    tax_rate_percent: 35,
    introvert_friendly: true,
    retiree_score: 8,
    tags: ['culture', 'food', 'walkable', 'vibrant'],
  },
  {
    name: 'Split',
    country: 'Croatia',
    continent: 'Europe',
    slug: 'split',
    monthly_rent_usd: 850,
    safety_score: 8,
    weather_score: 8,
    internet_speed_mbps: 220,
    tax_rate_percent: 20,
    introvert_friendly: true,
    retiree_score: 7,
    tags: ['coastal', 'history', 'mediterranean', 'retirees'],
  },
  {
    name: 'Tenerife',
    country: 'Spain',
    continent: 'Europe',
    slug: 'tenerife',
    monthly_rent_usd: 900,
    safety_score: 8,
    weather_score: 9,
    internet_speed_mbps: 400,
    tax_rate_percent: 24,
    introvert_friendly: true,
    retiree_score: 8,
    tags: ['island', 'beach', 'year-round-sun', 'remote-work'],
  },
  {
    name: 'Las Palmas',
    country: 'Spain',
    continent: 'Europe',
    slug: 'las-palmas',
    monthly_rent_usd: 850,
    safety_score: 8,
    weather_score: 9,
    internet_speed_mbps: 380,
    tax_rate_percent: 24,
    introvert_friendly: true,
    retiree_score: 8,
    tags: ['beach', 'nomad-hub', 'year-round-sun', 'walkable'],
  },
  {
    name: 'Crete',
    country: 'Greece',
    continent: 'Europe',
    slug: 'crete',
    monthly_rent_usd: 900,
    safety_score: 8,
    weather_score: 9,
    internet_speed_mbps: 180,
    tax_rate_percent: 22,
    introvert_friendly: true,
    retiree_score: 7,
    tags: ['mediterranean', 'beach', 'retirees', 'culture'],
  },
  {
    name: 'Algarve',
    country: 'Portugal',
    continent: 'Europe',
    slug: 'algarve',
    monthly_rent_usd: 1100,
    safety_score: 8,
    weather_score: 9,
    internet_speed_mbps: 420,
    tax_rate_percent: 28,
    introvert_friendly: true,
    retiree_score: 8,
    tags: ['coastal', 'international', 'retirees', 'remote-work'],
  },
  {
    name: 'Santa Familia',
    country: 'Belize',
    continent: 'Latin America',
    slug: 'santa-familia',
    monthly_rent_usd: 950,
    safety_score: 7,
    weather_score: 9,
    internet_speed_mbps: 60,
    tax_rate_percent: 0,
    introvert_friendly: true,
    retiree_score: 6,
    tags: ['tropical', 'nature', 'retirees', 'adventure'],
  },
  {
    name: 'Puerto Vallarta',
    country: 'Mexico',
    continent: 'Latin America',
    slug: 'puerto-vallarta',
    monthly_rent_usd: 1300,
    safety_score: 8,
    weather_score: 9,
    internet_speed_mbps: 200,
    tax_rate_percent: 30,
    introvert_friendly: false,
    retiree_score: 8,
    tags: ['beach', 'expat-friendly', 'retirees', 'healthcare'],
  },
  {
    name: 'Marsaxlokk',
    country: 'Malta',
    continent: 'Europe',
    slug: 'marsaxlokk',
    monthly_rent_usd: 1050,
    safety_score: 8,
    weather_score: 9,
    internet_speed_mbps: 350,
    tax_rate_percent: 24,
    introvert_friendly: true,
    retiree_score: 7,
    tags: ['coastal', 'mediterranean', 'retirees', 'slow-living'],
  },
  {
    name: 'Phuket',
    country: 'Thailand',
    continent: 'Asia',
    slug: 'phuket',
    monthly_rent_usd: 550,
    safety_score: 7,
    weather_score: 9,
    internet_speed_mbps: 300,
    tax_rate_percent: 0,
    introvert_friendly: false,
    retiree_score: 8,
    tags: ['beach', 'tropical', 'nomad-hub', 'expat-friendly'],
  },
  {
    name: 'Manila',
    country: 'Philippines',
    continent: 'Asia',
    slug: 'manila',
    monthly_rent_usd: 500,
    safety_score: 6,
    weather_score: 8,
    internet_speed_mbps: 150,
    tax_rate_percent: 0,
    introvert_friendly: false,
    retiree_score: 7,
    tags: ['english-friendly', 'urban', 'expat-friendly', 'affordable'],
  },
  {
    name: 'Bogotá',
    country: 'Colombia',
    continent: 'Latin America',
    slug: 'bogota',
    monthly_rent_usd: 600,
    safety_score: 6,
    weather_score: 8,
    internet_speed_mbps: 180,
    tax_rate_percent: 0,
    introvert_friendly: true,
    retiree_score: 8,
    tags: ['spring-weather', 'culture', 'affordable', 'nomad-hub'],
  },
  {
    name: 'Santo Domingo',
    country: 'Dominican Republic',
    continent: 'Latin America',
    slug: 'santo-domingo',
    monthly_rent_usd: 650,
    safety_score: 6,
    weather_score: 9,
    internet_speed_mbps: 120,
    tax_rate_percent: 0,
    introvert_friendly: false,
    retiree_score: 7,
    tags: ['caribbean', 'beach', 'expat-friendly', 'culture'],
  },
]

const cityBySlug = new Map(CITIES.map((city) => [city.slug, city]))

export function getCityDataBySlug(slug: string): CityData | null {
  return cityBySlug.get(slug) ?? null
}

export function getCitiesBySlugs(slugs: string[]): CityData[] {
  return slugs
    .map((slug) => getCityDataBySlug(slug))
    .filter((city): city is CityData => city !== null)
}
