/**
 * World Bank WGI — Political Stability and Absence of Violence/Terrorism
 * Percentile rank (0–100), 2023 update. Higher = more stable.
 *
 * Source: Worldwide Governance Indicators, World Bank (databank.worldbank.org)
 * Indicator: Political Stability: Percentile Rank (2023 values)
 * Citation: Worldwide Governance Indicators, World Bank (www.govindicators.org)
 *
 * Refresh annually when World Bank publishes updated WGI — edit WGI_2023_PV_PERCENTILE
 * in scripts/build-wgi-stability.mjs, then regenerate and patch cities:
 *   node scripts/build-wgi-stability.mjs
 *   node scripts/patch-cities-stability.mjs
 */

export const WGI_SOURCE = 'World Bank WGI, Political Stability percentile rank (2023)'

export const WGI_POLITICAL_STABILITY_PERCENTILE: Record<string, number> = {
  "Argentina": 52,
  "Armenia": 39,
  "Australia": 83,
  "Austria": 85,
  "Azerbaijan": 24,
  "Bahrain": 54,
  "Belgium": 73,
  "Bolivia": 43,
  "Brazil": 38,
  "Bulgaria": 59,
  "Canada": 82,
  "Chile": 66,
  "China": 32,
  "Colombia": 23,
  "Costa Rica": 72,
  "Croatia": 77,
  "Cuba": 58,
  "Cyprus": 69,
  "Czech Republic": 76,
  "Denmark": 90,
  "Dominican Republic": 51,
  "Ecuador": 32,
  "Egypt": 19,
  "El Salvador": 39,
  "Estonia": 79,
  "Ethiopia": 8,
  "Finland": 93,
  "France": 67,
  "Georgia": 49,
  "Germany": 78,
  "Greece": 59,
  "Guatemala": 29,
  "Honduras": 32,
  "Hong Kong": 68,
  "Hungary": 59,
  "Iceland": 92,
  "Indonesia": 29,
  "Ireland": 83,
  "Israel": 32,
  "Italy": 59,
  "Jamaica": 43,
  "Japan": 85,
  "Jordan": 43,
  "Kazakhstan": 49,
  "Kenya": 19,
  "Kuwait": 59,
  "Latvia": 73,
  "Lebanon": 10,
  "Lithuania": 76,
  "Luxembourg": 85,
  "Macau": 83,
  "Malaysia": 43,
  "Mexico": 23,
  "Mongolia": 73,
  "Morocco": 43,
  "Nepal": 39,
  "Netherlands": 83,
  "New Zealand": 92,
  "Nicaragua": 32,
  "Nigeria": 5,
  "Norway": 93,
  "Oman": 73,
  "Panama": 59,
  "Paraguay": 52,
  "Peru": 43,
  "Philippines": 29,
  "Poland": 73,
  "Portugal": 77,
  "Puerto Rico": 59,
  "Qatar": 77,
  "Romania": 59,
  "Russia": 24,
  "Saudi Arabia": 59,
  "Serbia": 52,
  "Singapore": 96,
  "Slovenia": 83,
  "South Africa": 38,
  "South Korea": 73,
  "Spain": 67,
  "Sri Lanka": 32,
  "Sweden": 85,
  "Switzerland": 91,
  "Taiwan": 83,
  "Tanzania": 49,
  "Thailand": 32,
  "Tunisia": 43,
  "Ukraine": 15,
  "United Arab Emirates": 81,
  "United Kingdom": 69,
  "United States": 72,
  "Uruguay": 83,
  "Uzbekistan": 39,
  "Vietnam": 49,
}

export function stabilityScoreForCountry(country: string): number {
  return WGI_POLITICAL_STABILITY_PERCENTILE[country] ?? 50
}
